[package]
name = "rdp_core"
version = "0.1.0"
edition = "2024"

[dependencies]
scrap = "0.5.0"
turbojpeg = { version = "0.4.3", features = ["image"] }
fast_image_resize = "2.7.2"
image = "0.25.1"
[lib]
name = "rdp_core"
crate-type = ["cdylib"]